### ISSUE TITLE
Bug: Recursive responses in Server module

### ISSUE THREAD

**Issue by matthewdwatkins** [luk3skyw4lker/node-ntp-sync#13]
The server module creates a recursive storm when sending responses. I believe this is caused by a bug on line 26 in server.js. It sets the address to "rinfo.server" when it should be "rinfo.address"

**Comment by luk3skyw4lker** [comment]
Solved in #14 by @boomfly!

I will be publishing the new version of the package by today or tomorrow, thanks for noticing!
