### ISSUE TITLE
Error with dgram

### ISSUE THREAD

**Issue by patryq955** [luk3skyw4lker/node-ntp-sync#2]
Can I use library in React application in client browser?

**Comment by luk3skyw4lker** [comment]
What is the error that you're having? I have already used it in an electron app but not specifically with React. If you tell me the error I can work a fix for you no prob.

**Comment by Lakshmikanthan0501** [comment]
I have same issue ?

**Comment by luk3skyw4lker** [comment]
It's currently not possible to use the library in the browser, the #12 issue speaks about the details.
