### ISSUE TITLE
Error: Can't resolve 'dgram' 

### ISSUE THREAD

**Issue by PJMoraDev** [luk3skyw4lker/node-ntp-sync#24]
Hi @luk3skyw4lker

I am trying to use your module but I get an error with one of its dependencies. This would be the error in console:

ERROR in ./node_modules/ntp-time/src/server.js 1:12-28
Module not found: Error: Can't resolve 'dgram' in 'path-to-my-project/node_modules/ntp-time/src'

**Comment by luk3skyw4lker** [comment]
If you're using it via browser, it won't work. Browsers don't allow communication via UDP thus making the module unusable. Can you please tell if you're using it via browser and what Node.js version you're using?

**Comment by PJMoraDev** [comment]
Yes i am using it via browser. My Node version is 20.12.2. Thank you very much.

**Comment by luk3skyw4lker** [comment]
Check out the #12. There is a discussion there on how to maybe fix the problem
